### ISSUE TITLE
review, part 1.

### ISSUE THREAD

**Issue by richfitz** [thibautjombart/outbreaker2#15]
# DESCRIPTION & NAMESPACE

* Does `compiler::cmpfun` make any difference? (probably remove it)
* Is `igraph` a hard dependency (it is not imported from and is notoriously heavy)
* If you are going to use `::` you do not need to use `importFrom`.  So you can cdelete these from the `cmpfun` package at least, probably others.
* you have two imports for modifyList, one of which is invalid

# README.md

Use `devtools::install_github` rather than `library(devtools)`

# Interface

Drop the startup message.  Imagine how annoying it would be if everything used them.

# Design

* **are you sure you don't want to add an S3 class attribute** to `outbreaker.config`?  It seems like it would be worth it for checking that it's been through your validator.

* **I would not make `loglike` and `posteriors` user-provideable** without a strong justification why this is needed.  You may have one for `loglike`, but `posteriors` surely follows from `priors + loglike`.  If you do keep this form, you will need to validate `posteriors` together with `priors` and `loglike` to make sure it all fits together appropriately.

This looks to be a problem at the moment for the loglike functions because you have:

```
    check.function.args <- function(f){
        args <- names(formals(f))
        if(identical(sort(args), c("data", "param")) ||
           identical(sort(args), c("data", "i", "param"))) {
            return(TRUE)
        } else {
            return(FALSE)
        }
    }
```

but elsewhere you will throw `i` into these as `NULL`.  So the checking is incomplete.  Premature optimisation is bad, but premature _generalisation_ can be just as bad - given this is unlikely to be robust consider removing it until everything else works properly?

Also, for all your `check.function.args` functions, I would be wary of comparing the names of the formals against a sorted character vecror; that requires that you will always refer to all arguments by name (i.e., any order is correct) but also prevent differently-named positional arguments (which is more R-ish).

* **Your prior handling is broken.** Unless I am missing something in the design, you let users provide priors for various bits of the model.  The default is for `mu` and `all` (I presume that `all` is special?).  The default `all` function runs:

```
return(prior.mu(param=param) + prior.pi(param=param))
```

but the `prior.mu` that is being called here will be the `outbreaker2::prior.mu`, not whatever was provided by the user as `mu`.  Note also that your defaults list does not include `pi`, even though `all` does use `pi`.

# Issues

Things don't seem stable across seeds for me:

```
```

# Random things

* In `outbreaker.data`, and likely elsewhere:

```
function(..., data=NULL){
    if(is.null(data)){
        data <- list(...)
    }
```

can be replaced by

```
function(..., data=list(...)) {
```

* Avoid `1:<x>` constructs in favour of `seq_len`.  I see 14 in the package and some of these will cause you grief with the corner case I'm sure.

* Turn on `options(warnPartialMatchAttr=TRUE, warnPartialMatchDollar=TRUE, warnPartialMatchArgs=TRUE)` and clean up the code a bit.  In particular I see partial argument matching for `rep` (`length` should be `length.out`).  Partial matching is a source of hard to find bugs and I always develop with the above options set.

# Testing

* **Do not use** `rm(list=ls())` in tests.  Or anywhere really.  This is not something that you should see committed in code.  It's not needed in tests because a `test_that_` block adds a scope for you - things created within the block will not persist after the block exits.  You can even use `on.exit()` within the blocks!  Within a test file a new scope is used, too.

* `skip_on_cran` should probably come out until you're ready for CRAN, so that tests run on Travis.  Or do they already?  I never know.

* Avoid using `expect_error()` without a string describing the error otherwise tests can appear to work for the wrong reason (that is, your test or code has a bug but it looks like the test passes).  I have been burnt by this so many times.  Compare these 4 lines:

  - `expect_error(outbreaker.config(n.iter=0))`
  - `expect_error(outbreaker_config(n.iter=0))`
  - `expect_error(outbreaker.config(n.iter=0), "n.iter is smaller than 2")`
  - `expect_error(outbreaker_config(n.iter=0), "n.iter is smaller than 2")`

(the same advice applies for `expect_warning` and `expect_error`)

# Documentation

* In `?outbreaker.config`, what is "seqTrack output"

# Style

Stuff in here is much more opinionated.

* I would remove the redundant comments, for example:

```
    ## return
    return(alpha)
```

or

```
} # end modify.defaults
```

And of course things like
```
    ## MODIFY DATA WITH ARGUMENTS ##
    data <- modify.defaults(defaults, data)
```

and my favourite:

```
    ## RETURN ##
    return(out)
```

as these really add nothing but increase the number of things that need to be read.  In general, comments really should document the "why", and the "what" only when the thing being done is especially complicated and needs explaining in another way.  Comments are great, but the comments that would really help here are not present (about the overall design of the package).  Because of the small, well named functions, most of the gruntwork code is essentially self documenting.

* I am not a fan of roxygen comments on unexported functions as I think it's weird for them to turn up in the help indices if they are not exported.

* Entirely style based, but if you want to conform to more common style guides:
  - Include a space between `if`, `for`, `while` and their opening paren (e.g., `if (foo) ...` not `if(foo) ...`
  - don't use `return` when dropping off the end of a function

* `fakeOutbreak` should be `fake.outbreak` to match the naming convention in the rest of the package

* Perhaps consider if you want single line if statements; rewrite

```
if(inherits(data$dates, "Date")) data$dates <- data$dates-min(data$dates)
```

as

```
if (inherits(data$dates, "Date")) {
  data$dates <- data$dates-min(data$dates)
}
```

(braces are optional but unthinking use of them can save some later drama; see apple's "goto fail").

* Consider `sprintf` over `paste` for complex string assembly:

```
stop(paste("\n\n PARANOID MODE DETECTED AN ERROR WHILE FINDING IMPORTS:\n",
           "at iteration ", i, ", ",
           "movement ", j, " (", names(moves)[j], ")",
           " with the following diagnostics:\n", diagnostic$msg, "\n\n",
           sep=""))
# vs:
stop(paste0(
  "\n\n PARANOID MODE DETECTED AN ERROR WHILE FINDING IMPORTS:\n",
  sprintf("at iteration %d, movement %d (%s) with the following diagnostics:\n%s",
          i, j, names(moves)[j], diagnostic$msg)))
```

Or you can go more hard-core and use classed errors which are lots of fun, but really only useful if you want to catch them specially.

* Prefer `::` over `importFrom`.  Once you get used to it, I find it makes reading code significantly easier because you know where your package hands over to other packages.  You could draw the line at core packages (stats especially, grDevices perhaps) but for packages like visNetwork, ape, etc, I like it (I did say this section was opinionated)

* SHOUTY.CASE things are usually constant -- but you add some to the data in `outbreaker.data`; that's a bit confusing there because the whole data thing is basically immutable so it's not clear why `MAX.RANGE` should be treated differently to `f.dens`.  I would go for lower case everywhere to be consistent.

* Avoid `sapply`.  It will eventually give you a hard to track down bug.  In cases like:

```
args.checks <- sapply(unlist(loglike), check.function.args)
```

consider

```
args.checks <- vapply(unlist(loglike), check.function.args, logical(1))
```

which indicates (and enforces) that the return value of `check.function.args` is a length-1 logical vector.  The result of this function will a logical vector of length `length(X)` always.  I use this so often that I usually define (in a file `R/utils.R`) functions

```
vlapply <- function(X, FUN, ...) {
  vapply(X, FUN, logical(1), ...)
}
viapply # same for integer(1)
vnapply # same for numeric(1)
vcapply # same for character(1)
```

* Be sparing with warnings.  They have their place but in cases like this:

```
    if(any(names(objects) == "")) {
        warning("all objects to be added to the environment of 'x' must be named; only adding named objects")
        to.keep <- names(objects) != ""
        objects <- objects[to.keep]
    }
```

this should be an error.  You lose 2 lines, some potential bugs, and no user gets a nasty surprise after running things for a week.  But then this function is likely to disappear anyway...

* Consider using `tibble`.  If you want abbreviated data.frames, tibble is nice and lightweight.

# Performance

I would check that your pre-allocated random numbers actually save any time - pull them out and see if things actually slow down appreciably.  I would be surprised if they do at present, despite adding considerable complexity.

For the small runs in the tests, with paranoid=TRUE, `outbreaker.find.imports` takes 96% of the time.  Note that `look.for.trouble` is only ~5% of the time, so not a huge drain.

In contrast `check.i` costs you ~19% of your time, but most of the time *you* provide `i` in the program so it should not need sanity checking.  In general sanity check user facing things but not internals.  And realistically this one is internal.  Possibly use `seq_int` rather than `seq.int` but better still to revisit how this is being dealt with, I think.  Note you also check `i` _three times_, including after it has been checked!

In general, some interface design here is needed:

* ll.all
  * ll.timing
    * ll.timing.infections
    * ll.timing.sampling

all run check.i; this should only be done on one user facing function, and then we can assume it's all correct after that.

Weirdly, `diag` turns up as a hotspot.  I have removed that in the PR for a reasonable performance gain

If it doesn't make sense to run the likelhoods with no data (which is probable) then I would enforce that in the data checks and get rid of the lines like:

    ## return 0 if no data
    if(data$N==0) return(0)

(also: that comment!)

**Comment by thibautjombart** [comment]
# Description / NAMESPACE
All done.

# README
All done.

# Interface
I'm still thinking about it ;)
