### ISSUE TITLE
review, part 2.

### ISSUE THREAD

**Issue by richfitz** [thibautjombart/outbreaker2#17]
This is much more brief, as I think this looks like a good building block and I think that to go further in depth I would probably need to either see a lot more documentation of the approach or sit together with you.  Probably the latter is the best thing to do at some point.

---

OK, my favourite thing about the current version is that I can see all the lines that are taking a long time.  Depressingly this includes `::` but that also means we're in the space where dropping things to C/Rcpp probably will be a bunch faster.  More depressingly because of using closures benchmarking is no longer informative with most of the time being spent in "anonymous functions".  But You probably have ~70% in the likelihood functions and most of the rest in the move functions.

The package is still a bit of a maze, but I think the flow is a lot saner than before.

# Interface

* startup message is still annoying.  I will mention this every time :)
* If you want a data.frame thing that prints just a few rows, consider making it a tbl_df with the tibble package:

```
loadNamespace("tibble") # in a package just be sure to Import it
class(out) <- c("outbreaker.chains", "tbl_df", "data.frame")
print.outbreaker.chains <- function(x, ...) {
    cat("\n\n ///// outbreaker results ///\n")
    cat("\nclass: ", class(x))
    cat("\ndimensions", nrow(x), "rows, ", ncol(x), "columns")
    NextMethod("print")
}
out
```

* I suggest adding an S3 class to config and making a print method.  Then in outbreaker.config have a bit:

```
if (is.null(config)) {
  config <- list(...)
  if (length(config) == 1L && inherits(config, "outbreaker.config")) {
    config <- config[[1]]
  }
}
if (inherits(config, "outbreaker.config")) {
  return(config)
}
```

Having the class attribute basically means it's been through validation so that can be skipped.  It also means it can be printed much more nicely.

* I still feel that the random vector bit should be pulled out for now, given how easy dropping most of this into C will be.  It will simplify your functions a bunch.  Have you benchmarked this before adding it? 

The other reason for removing it is it creates a dependency between the move functions and the cached random numbers - if a move function needs new random number types you have to add them (so it won't be extensible in the future).  You also end up with a 3rd 

* outbreaker.find.imports is documentated but not exported (and can't be created by users because it uses other nonexported functions).  Is that desirable?

* In `outbreaker.find.imports`, what is the point of:

```
            if (config$paranoid) {
                old.param <- param
            }
```

given `old.param` is never used?

# Issues

# User validation

More testing and validation (it never ends):

* `outbreaker.config(n.iter=Inf)`  will run for ever - check is.finite()
* `outbreaker.config(n.iter=NA_integer_)` confusing error message
* `outbreaker.config(n.iter=c(1, 2))` confusing warning
* `outbreaker.config(n.iter=integer(0))` confusing warning
* `outbreaker.config(move.mu=NA)` probably not wanted
* `outbreaker.config(sample.every=NA_integer_)` confusing error
* `outbreaker.config(sample.every=Inf)` probably not wanted
* `outbreaker.config(sd.pi=0)` probaby not ok
* `outbreaker.config(sd.pi=Inf)` probaby not ok

and so on.  I can show you my sanitisation approach some time.

* In `make.move.t.inf` you have parameters hard coded in the code:

```
        new.param$current.t.inf <- new.param$current.t.inf +
            sample(-1:1, size=length(new.param$current.t.inf), replace=TRUE, prob=c(.1,8,.1))
```

# Minor

* in your tests files, `context` calls should not start with "Test" (so `context("prior functions")` not `context("Test prior functions")`).
* Still lots of return comments:

```
grep -i '# *return' -A1 R/*.R
```

* Prefer `rowMeans(x)` and `colMeans(x)` to `apply(x, 1, mean)` and `apply(2, mean)` as they are both faster and easier to read.
* In the main `outbreaker` function, assign the return value of `outbreaker.move` to something other than `param` because it's a different *type* of object than the original `param` and I was confused reading the code

**Comment by thibautjombart** [comment]
Thanks! 
So, I've done everything except the following:

- *tibble* for `print.outbreaker.chains`; I tried it but preferred the custom printing, just a bit more informative

- random number pre-generation is actually faster (twice as fast in general, with less outlying times)

- ... (TBC)
