### ISSUE TITLE
Bug when w.dens has trailing zeroes

### ISSUE THREAD

**Issue by finlaycampbell** [thibautjombart/outbreaker2#30]
Just stumbled on an issue: my w.dens had a bunch of trailing zeroes which caused the starting loglike to be -Inf (the exponential tail added to w.dens was added after the trailing zeroes). Maybe we should check for trailing zeroes and remove them adding the tail? Probably not a very common error, but took a long time to find the bug!

**Comment by thibautjombart** [comment]
Good that you spotted that! Can you please:

1. add a check for this in `outbreaker_data`, with other checks for `w_dens`
2. add a unit test for this feature, to make sure the error is thrown when needed
3. PR against the current master

Thanks! :)

**Comment by finlaycampbell** [comment]
PR made!
